### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by Numidyum** [xyx0826/Bitsquid-Toolchain#1]
Hello, i wanna extract sound files from Helldivers 1, can you explain how to use this please

**Comment by xyx0826** [comment]
Hey, this project is modified from tools originally released by id-daemon on Zenhax. You will need a couple dependencies from the original release. Since the forum had shut down, you can find an archived version of the release post here: [Web Archive](https://web.archive.org/web/20220309155057/http://zenhax.com/viewtopic.php?t=1019)

1. Download the original release and unzip it somewhere
2. Either use the original sound extraction tool (`bitsquid_timpani.exe`) or compile the modified sound extraction tool from this project (`bstim.exe`) and place the compiled tool in the original release folder
3. To use the original sound extraction tool: `bitsquid_timpani.exe C:/path/to/Helldivers/content/<package name here> C:/path/to/Helldivers/content/<same package name here>.stream`
4. To use the modified sound extraction tool: `bstim.exe C:/path/to/Helldivers/content/<package name here>`

IIRC not all content files have audio in them, so you might need to write a wrapper script to call this tool on all content files in the game installation.

**Comment by Numidyum** [comment]
Hello again, i tried both original and modified bstim but im keep getting 
`Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at bitsquid_timpani.Program.Main(String[] args)`

**Comment by Numidyum** [comment]
> Hello again, i tried both original and modified bstim but im keep getting `Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow. at bitsquid_timpani.Program.Main(String[] args)`

At first i thought i was getting path wrong but when i tried with 
`bitsquid_unp_hd.exe "C:\Program Files (x86)\Steam\steamapps\common\Helldivers\contents\febd025b4693bb0f"` it unpacks but not the sound files so i am confused

**Comment by xyx0826** [comment]
Whoops sorry, I misread the forum post, my bad!

It looks like you indeed need to use `bitsquid_unp` (`bitsquid_unp_hd`, `bsunp`) to unpack _package files_ (files inside game directory) into resource files. This step also gets you `timpani_bank` files, which are audio banks. You then use `bitsquid_timpani` to unpack those audio banks into playable audio files.

**Comment by Numidyum** [comment]
Thank you so much it works now
